name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Обновили до v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flet
          
      - name: Build APK
        run: flet build apk
        
      - name: Upload APK
        uses: actions/upload-artifact@v4 # ВОТ ТУТ ГЛАВНОЕ ИСПРАВЛЕНИЕ (v4)
        with:
          name: darkgram-app
          path: build/apk/*.apk
